apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-sre-lab

resources:
  - ../../base/api-service/deployment.yaml
  - ../../base/api-service/service.yaml

# Parche sencillo de ejemplo (podr√≠as cambiar replicas, env vars, etc.)
patches:
  - target:
      kind: Deployment
      name: api-service
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-service
      spec:
        replicas: 1
